default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  # username: <%= ENV.fetch('DB_USER') { 'admin' } %>
  # password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>

development:
  <<: *default
  database: identifyy_development

test:
  <<: *default
  database: identifyy_test

staging:
  <<: *default
  database: core_staging

production:
  <<: *default
  database: identifyy_production
